name: Deploy Branch Preview

on:
  push:
    branches-ignore:
      - main # main branch is handled by Vercel's default production deployment

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy Preview
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # You need to add this to GitHub secrets
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: team_JnATE1AsaL0ebr2vzVyKdBk2
          vercel-project-id: prj_eB8H4Nr3CJ2jzBSW76YZ7n6hY6gd
